nome = input ("Qual o nome do vendedor? ")
salario = float(input ("Qual o salário fixo? R$"))
vendas = float(input ("Quantas vendas por mês? R$"))
comissao = (vendas * 0.15)
salario_final = round((salario + comissao), 2)

print ("===================")
print ("Informações de ", nome)
print ("-------------------")
print ("Salário fixo: R$", salario)
print ("Montante de vendas: R$", vendas)
print ("Portanto,", nome, "receberá R$", salario_final)
print ("===================")